### ISSUE TITLE
Deployment throughput costs in You Build It You Run It: incorrect attribution of Low to Impact for Run cost

### ISSUE THREAD

**Issue by tdpauw** [EqualExperts/you-build-it-you-run-it-playbook#3]
The _Run cost_ in _Deployment throughput costs in You Build It You Run It_ has Low for _Impact_ and no _TCO%_ value.

I guess the _Impact_ should be "Apex cost" and the _TCO%_ should be "Low".

**Comment by SteveSmithTech** [comment]
This is now fixed, thank you!
